---
- name: Create and Enable ADOM
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:
    - name: Create ADOM
      fmgr_generic:
        method: 'add'
        params:
          - url: 'dvmdb/adom'
            data:
              - name: "myadom"
              
    - name: Enable ADOM
      fmgr_generic:
        method: 'set'
        params:
          - url: '/cli/global/system/global'
            data:
              "adom-status": "enable"
