---
- name: Add FGTs to FortiManager
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:

  - name: Add my FGT
    fmgr_device:
      adom: "myadom"
      device_ip: "192.168.244.101"
      device_username: "admin"
      device_password: "fortinet"
      device_unique_name: "FGT1"
      device_serial: "FGVMULTM19000244"
      mode: "add"
      blind_add: "disable"
